DROP TABLE CUSTOMERS
IF EXISTS;

CREATE TABLE CUSTOMERS (
  ID             VARCHAR(25) PRIMARY KEY,
  NAME           VARCHAR(50),
  SURNAME        VARCHAR(50),
  ADDRESS        VARCHAR(150),
  NO_OF_ORDERS   BIGINT
);
