DROP TABLE CART_ITEM IF EXISTS;

CREATE TABLE CART_ITEM (
   ID VARCHAR(75),
   PRODUCT_ID VARCHAR(25),
   CART_ID varchar(50),
   QUANTITY BIGINT,
   FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID),
   FOREIGN KEY(CART_ID) REFERENCES CART(ID),
   CONSTRAINT CART_ITEM_PK PRIMARY KEY (ID,CART_ID)
);
